
[functions.refresh-feeds]
enabled = true
verify_jwt = false
import_map = "./functions/refresh-feeds/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/refresh-feeds/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/refresh-feeds/*.html" ]

[functions.cache-books]
enabled = true
verify_jwt = false
import_map = "./functions/cache-books/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cache-books/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cache-books/*.html" ]
